### PR TITLE
Add DKMS package with patched hpsa driver

### PR DESCRIPTION
**Pull request by artizirk**
This simplifies patching of the Linux kernel.

### CODE REVIEW

**Comment by im-0** [comment]
@artizirk, are you still interested in merging this? If yes, I propose the following:

* Move this into `contrib/dkms` instead of `kernel/dkms`.
* Create its own `.gitignore` there.
* Add a link to `contrib/dkms` into the main README.md.

**Comment by artizirk** [comment]
Yes, im still interested. Than you for the feedback, I will push requested changes soon.

**Comment by artizirk** [comment]
Hi @im-0, I have pushed the changes you requested. Check them out when you have time.

**Comment by im-0** [comment]
Thanks!

**Pull request merged**
